name: Integration

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  SonarQube:
    runs-on: self-hosted
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.event.repository.name }}
      - name: SonarQube [Pull Request]
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectName=${{ github.event.repository.name }}
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.working.directory=/tmp/sonar
            -Dsonar.projectBaseDir=${{ github.event.repository.name }}
            -Dsonar.qualitygate.wait=true
            -Dsonar.branch.name=main
        env:
          SONAR_HOST_URL: http://ci-cd.lucasmercier.com:9001
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}