name: Check Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  SonarQube:
    runs-on: self-hosted
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.event.repository.name }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.6.3
      - name: Maven command
        shell: bash
        run: mvn --file ${{ github.event.repository.name }}/pom.xml clean package
      - name: SonarQube [Pull Request]
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.pullrequest.provider=github
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.working.directory=/tmp/sonar
            -Dsonar.projectBaseDir=${{ github.event.repository.name }}
            -Dsonar.pullrequest.key=${{ github.event.number }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_HOST_URL: http://ci-cd.lucasmercier.com:9001
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}